name: CI

on:
  push:


jobs:
  build_test_env:
    name: Buld test environment
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: docker/docker-build-push@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: docker.pkg.github.com
          image: rafsodc/helpers
          githubOrg: rafsodc
          dockerfile: docker/docker_test_container
          tag_with_ref: true