name: CI

on:
  push:


jobs:
  build_test_env:
    name: Buld test environment
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Build
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: rafsodc/helpers
          dockerfile: docker/docker_test_container
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}