name: CD

on:
  push:


jobs:
  build_test_env:
    name: Buld test environment
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          registry: docker.pkg.github.com
          repository: rafsodc/helpers/docker_test_env
          dockerfile: docker/docker_test_container
          tag_with_ref: true
      - name: Build
          # Frustratingly require as you cannot pull from GitHub without username and password, which is not supported by jobs.containers
          uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.DPASSWORD }}
            registry: docker.pkg.github.com
            repository: jdipper/docker_test_env
            dockerfile: docker/docker_test_container
            tag_with_ref: true
