name: CD

on:
  push:


jobs:
  build_test_env:
    name: Buld test environment
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build to Dockerhub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_TOKEN }}
          repository: ${{ secrets.DH_USERNAME }}/docker_test_env
          dockerfile: docker/docker_test_container
          tag_with_ref: true
